"""initial schema

Creates shows -> seasons -> episodes -> artwork, plus users and publish_runs.

Index rationale (each maps to a hot query):
  * ix_shows_status_section  -> publish + validation scan "published shows by section"
  * ix_shows_title           -> CMS/viewer title search (ILIKE)
  * ix_episodes_status       -> validation/publish filter episodes by status
  * ix_episodes_content_group-> the language-collapse GROUP BY content_group
  * ix_episodes_title        -> episode-title search
  * uq_episode_group_language-> enforces the (content_group, language) rule in the DB
  * uq_artwork_episode_kind  -> one image per (episode, slot); re-upload replaces

Revision ID: 9623b730017e
Revises:
Create Date: 2026-08-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9623b730017e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('catalog_key', sa.String(length=512), nullable=True),
    sa.Column('show_count', sa.Integer(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.CheckConstraint("outcome in ('success','blocked','failed')", name='ck_run_outcome'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_started', 'publish_runs', ['started_at'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('draft','published')", name='ck_show_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_shows_status_section', 'shows', ['status', 'section'], unique=False)
    op.create_index('ix_shows_title', 'shows', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.CheckConstraint("role in ('editor','admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('is_trailer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'season_number', name='uq_season_show_number')
    )
    op.create_index('ix_seasons_show', 'seasons', ['show_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content_group', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('draft','published')", name='ck_episode_status'),
    sa.CheckConstraint('duration_seconds is null or duration_seconds > 0', name='ck_episode_duration_pos'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_group', 'language', name='uq_episode_group_language')
    )
    op.create_index('ix_episodes_content_group', 'episodes', ['content_group'], unique=False)
    op.create_index('ix_episodes_season', 'episodes', ['season_id'], unique=False)
    op.create_index('ix_episodes_status', 'episodes', ['status'], unique=False)
    op.create_index('ix_episodes_title', 'episodes', ['title'], unique=False)
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind in ('poster','banner','thumbnail')", name='ck_artwork_kind'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'kind', name='uq_artwork_episode_kind')
    )
    op.create_index('ix_artwork_episode', 'artwork', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artwork_episode', table_name='artwork')
    op.drop_table('artwork')
    op.drop_index('ix_episodes_title', table_name='episodes')
    op.drop_index('ix_episodes_status', table_name='episodes')
    op.drop_index('ix_episodes_season', table_name='episodes')
    op.drop_index('ix_episodes_content_group', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('ix_seasons_show', table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('users')
    op.drop_index('ix_shows_title', table_name='shows')
    op.drop_index('ix_shows_status_section', table_name='shows')
    op.drop_table('shows')
    op.drop_index('ix_runs_started', table_name='publish_runs')
    op.drop_table('publish_runs')
    # ### end Alembic commands ###
